[
	"A-Trak",
	"A.C. Newman",
	"Arkells",
	"Astrocolor",
	"Bear Mountain",
	"Boys Noize",
	"Chromeo",
	"Crystal Castles",
	"Dark Horses",
	"Datsik",
	"DCF",
	"Death From Above 1979",
	"Dirty Ghosts",
	"Dubmatix",
	"Egyptrixx",
	"Electric Youth",
	"Emily Haines",
	"Fan Death",
	"Fur Trade",
	"Gazelle Twin",
	"Harrison",
	"Hiawatha",
	"Hot As Sun",
	"Huoratron",
	"Jack Novak",
	"JOOJ",
	"k-os",
	"Kay",
	"Kinnie Starr",
	"Leisure Cruise",
	"Let’s Go To War",
	"Lights",
	"Lindi Ortega",
	"Magneta Lane",
	"Metric",
	"Mixhell",
	"Modern Superstitions",
	"Moon King",
	"Mother Mother",
	"MSTRKRFT",
	"O’Luge",
	"Ohbijou",
	"Operators",
	"Panurge",
	"Purity Ring",
	"Rush Midnight",
	"Ryan Hemsworth",
	"Sebastien Grainger",
	"Seoul",
	"Sheldon Scott",
	"Silver Starling",
	"Terry Lynn",
	"The Burning Hell",
	"The New Pornographers",
	"Tiga",
	"Tre Mission",
	"We Are Enfant Terrible",
	"Wolf & Cub "
]